#pragma once

enum
{
	LT_MEM_TYPE_UNKNOWN = 0,
	LT_MEM_TYPE_MISC,
	LT_MEM_TYPE_TEXTURE, 
	LT_MEM_TYPE_MODEL,
	LT_MEM_TYPE_SPRITE,
	LT_MEM_TYPE_SOUND,
	LT_MEM_TYPE_OBJECT,
	LT_MEM_TYPE_WORLD,
	LT_MEM_TYPE_HEIGHTMAP,
	LT_MEM_TYPE_PCX,
	LT_MEM_TYPE_MUSIC,
	LT_MEM_TYPE_UI,
	LT_MEM_TYPE_MEM,
	LT_MEM_TYPE_STRING,
	LT_MEM_TYPE_HASHTABLE,
	LT_MEM_TYPE_WORLDTREE,
	LT_MEM_TYPE_NETWORKING,
	LT_MEM_TYPE_RENDERER,
	LT_MEM_TYPE_RENDER_SHADER,
	LT_MEM_TYPE_RENDER_WORLD,
	LT_MEM_TYPE_RENDER_LIGHTMAP,
	LT_MEM_TYPE_RENDER_LIGHTGROUP,
	LT_MEM_TYPE_RENDER_TEXTURESCRIPT,
	LT_MEM_TYPE_CONSOLE,
	LT_MEM_TYPE_INTERFACEDB,
	LT_MEM_TYPE_INPUT,
	LT_MEM_TYPE_PROPERTY,
	LT_MEM_TYPE_CLIENTSHELL,
	LT_MEM_TYPE_OBJECTSHELL,
	LT_MEM_TYPE_CLIENTFX,
	LT_MEM_TYPE_GAMECODE,

	LT_NUM_MEM_TYPES
};

#ifdef LTMEMTRACK
#else
#define LT_MEM_TRACK_ALLOC(ltStatement, ltAllocType) ltStatement
#define LT_MEM_TRACK_FREE(ltStatement) ltStatement
#define LT_MEM_TRACK_REALLOC(ltStatement, ltAllocType) ltStatement
#endif